graph TD
    subgraph Utilisateur
        U[Utilisateur]
    end

    subgraph Interface_Utilisateur
        UI[Interface upload HTML_JS]
    end

    subgraph Serveur_IA_Backend
        BE[Backend Flask]
        MODEL[Modele IA Inference]
    end

    subgraph Stockage
        FS[Fichiers temporaires]
        DB[Base de donnees]
    end

    U --> UI
    UI --> BE
    BE --> FS
    FS --> MODEL
    MODEL --> BE
    BE --> UI
    BE --> DB
